server:
  error:
    include-message: always
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: 10m

logging:
  level:
    root: warn

cache:
  hazelcast:
    hero:
      ttl: 60
    heroes:
      ttl: 360

threadpool:
  coreSize: 10
  maxSize: 50
  queueCapacity: 100