spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: test
#  cache:
#      type: hazelcast

api:
  url: https://superhero-search.p.rapidapi.com/api/
  header:
    key:
      name: X-RapidAPI-Key
      value: 5ce0216210msh4bdfcf6de5e3d81p188f53jsne19902040d6a
    host:
      name: X-RapidAPI-Host
      value: superhero-search.p.rapidapi.com

